/*
 * Utility functions
 */

/**
 * Forwards all notifications from the source observable to the given subject.
 *
 * @param  Rx.Observable source the origin observable
 * @param  Rx.Subject subject   the destination subject
 * @return Rx.Disposable        a disposable generated by a subscribe method
 */
function replicate(source, subject) {
  return source.subscribe(function replicationSubscriber(x) {
    subject.onNext(x);
  })
}

module.exports = {
  replicate: replicate
};
